name: aimplant
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - ca-certificates
  - openssl
  - huggingface_hub
  - certifi
  - transformers
  - accelerate
  - scikit-learn
  - seaborn
  - jupyter
  - h5py

